### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by nyov**
Also rewrote this to use a `namedtuple` for logins/sites,
generalized the autodetected profile paths to include non-default profiles
(, and to what I think is a slightly better format according to pep8 for the imports)

### CODE REVIEW

**Comment by hartwork** [comment]
Hi!

While I'm happy to see a new pull request, I don't like the fact that a lot of unrelated changes all make a single commit. To give emaples, besides pysqlite2 support I see:
* Re-formatting of existing imports (check make target "isort")
* Change of globbing patterns
* Re-formatting of existing code, e.g. the SQL query (including some breaking pep8, check make target "pep8")
* Introduction of MozLogin

Please turn that into commits with distinct semantics each and use make targets "isort" and "pep8". Okay?

**Comment by nyov** [comment]
I suppose I can split them.
What is isort?

**Comment by hartwork** [comment]
> What is isort?

isort is https://github.com/timothycrosley/isort
`pip install isort` or so might work.

**Comment by nyov** [comment]
I would disagree with enforcing isort. It's okay as a reference.

And forcing `-m 2` is counter to pep8's [recommendation for grouping](https://www.python.org/dev/peps/pep-0008/#maximum-line-length).
> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

If you believe in forcing this, option 3 would make more sense for the least amount of unrelated LOC changes and resorting in future commits?

**Comment by hartwork** [comment]
> I would disagree with enforcing isort. It's okay as a reference.

The pull request currently re-formats existing import lines. If it does so, it should be a distinct commit in any case. For new import lines, I would also not request a specific import line style. I would only run isort some time myself, later.

> If you believe in forcing this, option 3 would make more sense for the least amount of unrelated LOC changes and resorting in future commits?

I have switched to `-m 4` in commit 6ba77a90a0b000f7601a67c098cc3cadc251b25e now. Are you okay with `-m 4`?

**Comment by nyov** [comment]
Sure, let's not get too caught up in semantics.
Let me know if the split commits are okay now.

**Comment by hartwork** [comment]
I have cheery-picked these commits:
* 6e26a30579ba52f215c2e3b196f014e3f2a59199 now is  09594137b5cc35864ec321f63a8cacd27335e761 (same content)
* baabf095635cb69a51798439f7328d4158ec535e now is  b98c5e93b970ced5b6b5048666ee01dccd27294d(without the .gitignore update, separate commit please)
* af82ceab3c79facda03beeb29b45bab006f5a96d now is 75f2113cad87bae9ec0246681cd1666fbc98b2e6 (without the changes in whitespace)

That saved the merge commit (that would pull in pre-review commits) and commits with mixed semantics.

**Comment by hartwork** [comment]
Main changes cherry-picked, closing.

**Pull request closed without merging**
